### ISSUE TITLE
globalContextManager.active doesn't provide context of root span correctly

### ISSUE THREAD

**Issue by dankhan-helmet** [Workiva/opentelemetry-dart#189]
**Describe the bug**
When I use the `traceContextSync` or `traceContext` helper functions, the first call to `globalContextManager.active` presumably to get the root span if no others have been created, returns a NonRecordingSpan with an invalid spanId (0000000) instead of the root span with spanId ([]).

I assume the root span would be setup automatically so that there's always a starting context available?  Maybe this assumption is wrong, but it's not clear from the docs/README.  

The span exports to Jaegar okay (but it could just ignore a missing parent span so maybe the problem isn't being shown there, but exporting the same data to honeycomb, the problem is more obvious as they render the root span as a missing span).

**Steps to reproduce**
```
final tp =
      TracerProviderBase(processors: [SimpleSpanProcessor(ConsoleExporter())]);
  registerGlobalTracerProvider(tp);

  final cm = ZoneContextManager();
  registerGlobalContextManager(cm);

  traceContextSync<void>("My Span", (Context context) {
    spanFromContext(globalContextManager.active).setAttributes([
        Attribute.fromBoolean('test', true),
      ]);
  });
```

**What did you expect to see?**
Expected that the first call to globalContextManager.active would get the root context and a valid recording span

**What did you see instead?**
It returns a non-recording invalid span id span with parentId = 00000000 instead of [].
![CleanShot 2024-09-03 at 12 51 49](https://github.com/user-attachments/assets/bf598af7-720e-4aaf-888c-7cd93ed014b7)

**What version and what artifacts are you using?**
Artifacts: (`opentelemetry-api`, `opentelemetry-sdk`, which BatchSpanProcessor, )
Version: opentelemetry: ^0.18.6
How did you reference these artifacts? (excerpt from your `pubspec.lock`, `pubspec.yaml`, etc)

```
opentelemetry:
    dependency: "direct main"
    description:
      name: opentelemetry
      sha256: "7ae74cb06c079bc1c69160d84eaf3b386922af5b7b3c77e260d4dc265b1dbb07"
      url: "https://pub.dev"
    source: hosted
    version: "0.18.6"
```

**Environment**
Dart Version: Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
OS: Flutter (Channel stable, 3.19.2, on macOS 13.6.4 22G513 darwin-arm64, locale en-NZ)

**Additional context**
